---
title: "GSE4780"
author: "Kaitlyn O'Shea"
date: "10/1/2019"
output: html_document
---

## ones sample does not have recurrence nor grade data

```{r setup}
knitr::opts_chunk$set(echo = TRUE,
                      eval = TRUE)
```

```{r install_packages, eval = FALSE}
## require BioManager
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("GEOquery") 
```

```{r libraries, message=FALSE, warning=FALSE}
## libraries needed
library("tidyverse")
library("GEOquery")
library("here")
```

## Get GSE4780 from GEO
```{r Geo_download, message=FALSE, warning=FALSE}
## Download dataset from GEO, save downloaded files in the same folder as this .Rmd file.
dir.create(file.path("raw","gse4780"), recursive = TRUE)
gse4780 <- getGEO("gse4780",  # sample accession 
                   destdir = file.path("raw","gse4780"),
                   GSEMatrix = TRUE,
                   AnnotGPL = TRUE)
```

## Clinical Data from Dataset
```{r ClinicalDataExtract}
## index into data list and extract clinical data
gse4780_cd <-
                  gse4780[["GSE4780-GPL570_series_matrix.txt.gz"]] %>%           # index into list 
                  phenoData() %>%             # select phenoData
                  pData() %>%                 # apply pData
                  as_tibble() %>%             # tidy friendly
                  select("geo_accession" = geo_accession,
                         "sample_id" = title, # do we need sample name and accession number?
                         "description" = `description` # needs to be cleaned
                         ) 

gse4780_pheno <- gse4780_cd %>%         # rename and adjust variables
                     mutate(
                            "grade" = str_sub(description, -1),     # pull out the grade from the description data
                            "recurrence" = str_split(string = description,
                                                     pattern = " ",
                                                     simplify = T)[,2],     # pull out the recurrence from the description data
                            "tissue" = "meningioma"
                            ) %>% mutate(
                                "grade" = factor(grade, 
                                                levels = c("1", "2", "3"), 
                                                labels = c("I", "II", "III")
                                             ),
                                "recurrence" = factor(recurrence,
                                                      levels = c("Primary", "Recurrent"),
                                                      labels = c("primary", "recurrent")
                                                  )    
                    ) %>% select(
                                 geo_accession,
                                 sample_id,
                                 grade,
                                 recurrence,
                                 tissue
                                ) %>%
                                      mutate_if(is.character, as.factor)
```

## Expression Data from Dataset
```{r ExpressionDataExtract}
## index into data list and extract expression table.
gse4780_exprs <- 
                  gse4780[["GSE4780-GPL570_series_matrix.txt.gz"]] %>%   # index into list 
                  exprs() %>%         # select expression data
                  as_tibble()         # tidy friendly

## index into data list and extract gene feature data
gse4780_feature <- 
                  gse4780[["GSE4780-GPL570_series_matrix.txt.gz"]] %>%  # index into list 
                  fData() %>%        # select feature data
                  as_tibble()        # tidy friendly
```

## Transform Expression Data
``` {r ExpressionDataTransform}
# function to find standard deviation of each probe across all tumors
rowsd <- function(x) {
                      sqrt(
                        rowSums((x - rowMeans(x))^2)/
                          (dim(x)[2] - 1)
                        )
}

## keep only the probe with greatest variability across tumors as rna variable and gene names
gse4780_rna <-
               bind_cols(gse4780_feature["Gene symbol"], gse4780_exprs) %>% # add gene name to expression data
               rename("gene" = "Gene symbol") %>%                             # rename name variable as 'gene' 
               filter(gene != "") %>%                                         # keep only data for named genes
               mutate(sd = rowsd(.[,-1])) %>%                                 # calculate sd for each probe, index out gene name
               group_by(gene) %>%                                             # group probes by gene
               filter(sd == max(sd)) %>%                                      # keep the probe with the max variation for each gene
               ungroup() %>%                                                  # ungroup by genes 
               select(-sd) %>%                                                # select all but sd column
               pivot_longer(-gene,                                            # do not group by gene 
                            names_to = "geo_accession",                       # 'key' via gather
                            values_to = "value") %>%                          
               mutate("logvalue" = log2(value)) %>%                           # log2 transform expression for variance stabilization 
                group_by(gene) %>%                                             # standardize for cross data set comparison
                mutate("standardized" = (logvalue - mean(logvalue))/           # center at mean for gene 
                                         sd(logvalue),                         # scale by sd for gene
                       ) %>%
                ungroup() %>%                                                  # ungroup by genes 
                select(-value, -logvalue) %>%                                  # select all but sd column
                pivot_wider(names_from = "gene",                               # final format genes as rows
                            values_from = "standardized")                      # final format expression across accession as columns    
```

## Dataset for Analysis
```{r FinalDataset}
## combine phenotype and expression data for workable data
gse4780_data <- inner_join(gse4780_pheno, gse4780_rna, 
                            by = "geo_accession")          # match by accession

## create metatag for dataset
gse4780_info <-  
                list(
                     name = "Scheck_A",              # author
                     accession = "GSE4780",                # dataset accession 
                       # the following are logical to determine clinical data available for dataset
                      geo_accession = "geo_accession" %in% colnames(gse4780_pheno),
                      sample_id = "sample_id" %in% colnames(gse4780_pheno),
                      age = "age" %in% colnames(gse4780_pheno),
                      sex = "sex" %in% colnames(gse4780_pheno),
                      grade = "grade" %in% colnames(gse4780_pheno),
                      histology = "histology" %in% colnames(gse4780_pheno),
                      type = "type" %in% colnames(gse4780_pheno),
                      location = "location" %in% colnames(gse4780_pheno),
                      mib1_index = "mib1_index" %in% colnames(gse4780_pheno),
                      recurrence = "recurrence" %in% colnames(gse4780_pheno),
                      recurrence_yrs = "recurrence_yrs" %in% colnames(gse4780_pheno),
                      recurrence_freq = "recurrence_freq" %in% colnames(gse4780_pheno),
                      followup_days = "followup_days" %in% colnames(gse4780_pheno),
                      survival_yrs = "survival_yrs" %in% colnames(gse4780_pheno),
                      vital_indicator = "vital_indicator" %in% colnames(gse4780_pheno),
                      tissue = "tissue" %in% colnames(gse4780_pheno),
                      progression = "progression" %in% colnames(gse4780_pheno),
                      radiation = "radiation" %in% colnames(gse4780_pheno),
                      rna_integrity ="rna_integrity" %in% colnames(gse4780_pheno),

                      sample_numbers = nrow(gse4780_data) # number of samples
                     )

## create dataset as list 
Scheck_A <- list(
                   dataset_info = gse4780_info,             # metatag
                   clinical_data = gse4780_pheno,           # clinical data
                   expression_data = gse4780_rna,           # expression data
                   data = gse4780_data,                     # combined, workable data
                   full_GEO = gse4780                       # full original download from GEO
                   )
```

```{r}
save(Scheck_A, file = here("datasets","GSE4780_Scheck_A_KO.Rda"))
```

