---
title: "GSE58037"
author: "Kaitlyn O'Shea"
date: "9/30/2019"
output: html_document
---

## some samples have no recurrence nor grade data

```{r setup}
knitr::opts_chunk$set(echo = TRUE,
                      eval = TRUE)
```

```{r install_packages, eval = FALSE}
## require BioManager
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("GEOquery") 
```

```{r libraries, message=FALSE, warning=FALSE}
## libraries needed
library("tidyverse")
library("GEOquery")
library("here")
```

## Get GSE58037 from GEO
```{r Geo_download, message=FALSE, warning=FALSE}
## Download dataset from GEO, save downloaded files in the same folder as this .Rmd file.
dir.create(file.path("raw","gse58037"), recursive = TRUE)
gse58037 <- getGEO("gse58037",  # sample accession 
                   destdir = file.path("raw","gse58037"),
                   GSEMatrix = TRUE,
                   AnnotGPL = TRUE)
```

## Clinical Data from Dataset
```{r ClinicalDataExtract}
## index into data list and extract clinical data
gse58037_cd <-
                  gse58037[["GSE58037_series_matrix.txt.gz"]] %>%           # index into list 
                  phenoData() %>%             # select phenoData
                  pData() %>%                 # apply pData
                  as_tibble() %>%             # tidy friendly
                  select("geo_accession" = geo_accession,
                         "sample_id" = `ID:ch1`,   
                         "grade" = `grade:ch1`,  
                         "recurrence" = `isprimary:ch1`,
                         "radiation" = `radiation:ch1`,
                         "rna_integrity" = `rin:ch1`
                         ) 

gse58037_pheno <- gse58037_cd %>%         # rename and adjust variables
                     mutate(
                            "grade" = factor(grade, 
                                             levels = c("1", "2", "3"), 
                                             labels = c("I", "II", "III")
                                             ),
                            "recurrence" = factor(recurrence,
                                                  levels = c("PRIMARY", "Recurrent"),
                                                  labels = c("primary", "recurrent")
                                                  ),    
                            "radiation" = factor(radiation,
                                                 levels = c("Yes", "No", "Unknown"),
                                                 labels = c("yes", "no", "unknown")
                                                  ),
                            "rna_integrity" = as.numeric(rna_integrity),
                            "tissue" = "meningioma"    
                    ) %>%
                      mutate_if(is.character, as.factor)
```

## Expression Data from Dataset
```{r ExpressionDataExtract}
## index into data list and extract expression table.
gse58037_exprs <- 
                  gse58037[["GSE58037_series_matrix.txt.gz"]] %>%   # index into list 
                  exprs() %>%         # select expression data
                  as_tibble()         # tidy friendly

## index into data list and extract gene feature data
gse58037_feature <- 
                  gse58037[["GSE58037_series_matrix.txt.gz"]] %>%  # index into list 
                  fData() %>%        # select feature data
                  as_tibble()        # tidy friendly
```

## Transform Expression Data
``` {r ExpressionDataTransform}
# function to find standard deviation of each probe across all tumors
rowsd <- function(x) {
                      sqrt(
                        rowSums((x - rowMeans(x))^2)/
                          (dim(x)[2] - 1)
                        )
}

## keep only the probe with greatest variability across tumors as rna variable and gene names
gse58037_rna <-
               bind_cols(gse58037_feature["Gene symbol"], gse58037_exprs) %>%  # add gene name to expression data
               rename("gene" = "Gene symbol") %>%                              # rename name variable as 'gene' 
               filter(gene != "") %>%                                          # keep only data for named genes
                mutate(sd = rowsd(.[ , -1])) %>%                               # calculate sd for each probe, index out gene name
                group_by(gene) %>%                                             # group probes by gene
                filter(sd == max(sd)) %>%                                      # keep the probe with the max variation for each gene
                filter(row_number() == 1) %>%                                  # remove duplicates
                ungroup() %>%                                                  # ungroup by genes 
                select(-sd) %>%                                                # select all but sd column
                pivot_longer(-gene,                                            # do not group by gene 
                             names_to = "geo_accession",                       # 'key' via gather
                             values_to = "value") %>%
                mutate("logvalue" = log2(value)) %>%                           # log2 transform expression for variance stabilization 
                group_by(gene) %>%                                             # standardize for cross data set comparison
                mutate("standardized" = (logvalue - mean(logvalue))/           # center at mean for gene 
                                         sd(logvalue),                         # scale by sd for gene
                       ) %>%
                ungroup() %>%                                                  # ungroup by genes 
                select(-value, -logvalue) %>%                                  # select all but sd column
                pivot_wider(names_from = "gene",                               # final format genes as rows
                            values_from = "standardized")                      # final format expression across accession as columns  
```

## Dataset for Analysis
```{r FinalDataset}
## combine phenotype and expression data for workable data
gse58037_data <- inner_join(gse58037_pheno, gse58037_rna, 
                            by = "geo_accession")   # match by accession

## create metatag for dataset
gse58037_info <-  
                list(
                     name = "Clark_V",               # author
                     accession = "GSE58037",         # dataset accession 
                     # the following are logical to determine clinical data available for dataset
                     geo_accession = "geo_accession" %in% colnames(gse58037_pheno),
                      sample_id = "sample_id" %in% colnames(gse58037_pheno),
                      age = "age" %in% colnames(gse58037_pheno),
                      sex = "sex" %in% colnames(gse58037_pheno),
                      grade = "grade" %in% colnames(gse58037_pheno),
                      histology = "histology" %in% colnames(gse58037_pheno),
                      type = "type" %in% colnames(gse58037_pheno),
                      location = "location" %in% colnames(gse58037_pheno),
                      mib1_index = "mib1_index" %in% colnames(gse58037_pheno),
                      recurrence = "recurrence" %in% colnames(gse58037_pheno),
                      recurrence_yrs = "recurrence_yrs" %in% colnames(gse58037_pheno),
                      recurrence_freq = "recurrence_freq" %in% colnames(gse58037_pheno),
                      followup_days = "followup_days" %in% colnames(gse58037_pheno),
                      survival_yrs = "survival_yrs" %in% colnames(gse58037_pheno),
                      vital_indicator = "vital_indicator" %in% colnames(gse58037_pheno),
                      tissue = "tissue" %in% colnames(gse58037_pheno),
                      progression = "progression" %in% colnames(gse58037_pheno),
                      radiation = "radiation" %in% colnames(gse58037_pheno),
                      rna_integrity ="rna_integrity" %in% colnames(gse58037_pheno),

                     sample_numbers = nrow(gse58037_data) # number of samples 
                     )

## create dataset as list 
Clark_V <- list(
                dataset_info = gse58037_info,             # metatag
                clinical_data = gse58037_pheno,           # clinical data
                expression_data = gse58037_rna,           # expression data
                data = gse58037_data #,                     # combined, workable data
             #   full_GEO = gse58037                       # full original download from GEO
)
```
```{r}
save(Clark_V, file = here("datasets","GSE58037_Clark_V_KO.Rda")) 
```