---
title: "GSE62381"
author: "Kaitlyn O'Shea"
date: "10/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval = FALSE)
```

```{r install_packages, eval = FALSE}
## require BioManager
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("GEOquery") 
```

```{r libraries, message=FALSE, warning=FALSE}
## libraries needed
library("tidyverse")
library("GEOquery")
```

## Get GSE62381 from GEO
```{r Geo_download, message=FALSE, warning=FALSE}
## Download dataset from GEO, save downloaded files in the same folder as this .Rmd file.
dir.create(file.path("raw","gse62381"), recursive = TRUE)
gse62381 <- getGEO("gse62381",  # sample accession 
                   destdir = file.path("raw","gse62381"),
                   GSEMatrix = TRUE,
                   AnnotGPL = TRUE)
```

## Clinical Data from Dataset
```{r ClinicalDataExtract}
## index into data list and extract clinical data
gse62381_pheno <-
                  gse62381[[1]] %>%           # index into list 
                  phenoData() %>%             # select phenoData
                  pData() %>%                 # apply pData
                  as_tibble() %>%             # tidy friendly
                  select("geo_accession" = geo_accession,
                         "sample_id" = title, # do we need sample name and accession number?
                         "disease" = `disease state:ch1` # this is a mixed variable between grade and histology
                         ) 
```

## Expression Data from Dataset
```{r ExpressionDataExtract}
## index into data list and extract expression table.
gse62381_exprs <- 
                  gse62381[[1]] %>%   # index into list 
                  exprs() %>%         # select expression data
                  as_tibble()         # tidy friendly

## index into data list and extract mirna feature data
gse62381_feature <- 
                  gse62381[[1]] %>%  # index into list 
                  fData() %>%        # select feature data
                  as_tibble()        # tidy friendly
```

## Transform Expression Data
``` {r ExpressionDataTransform}
# function to find standard deviation of each probe across all tumors
rowsd <- function(x) {
                      sqrt(
                        rowSums((x - rowMeans(x))^2)/
                          (dim(x)[2] - 1)
                        )
}

## keep only the probe with greatest variability across tumors as rna variable and mirna names
gse62381_rna <-
               bind_cols(gse62381_feature["ID"], gse62381_exprs) %>%          # add mirna name to expression data
               rename("mirna" = "ID") %>%                                     # rename name variable as 'mirna' 
               filter(mirna != "") %>%                                        # keep only data for named mirna
               pivot_longer(-mirna,                                           # do not group by mirna 
                            names_to = "geo_accession",                       # 'key' via gather
                            values_to = "value") %>%                          
               pivot_wider(names_from = "mirna",                              # final format mirnas as rows
                            values_from = "value")                            # final format expression across accession as columns    

```

## Dataset for Analysis
```{r FinalDataset}
## combine phenotype and expression data for workable data
gse62381_data <- inner_join(gse62381_pheno, gse62381_rna, 
                            by = "geo_accession")          # match by accession

## create metatag for dataset
gse62381_info <-  
                list(
                     name = "Drusco_A",              # author
                     accession = "GSE62381"                # dataset accession 
                     )

## create dataset as list 
Drusco_A <- list(
                        dataset_info = gse62381_info,      # metatag
                        data = gse62381_data)              # workable data
```
