---
title: "GSE83933"
author: "Kaitlyn O'Shea"
date: "9/30/2019"
output: html_document
---


```{r setup}
knitr::opts_chunk$set(echo = TRUE,
                      eval = TRUE)
```

```{r install_packages, eval = FALSE}
## require BioManager
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("GEOquery") 
```

```{r libraries, message=FALSE, warning=FALSE}
## libraries needed
library("tidyverse")
library("GEOquery")
library("here")
```

## Get GSE83933 from GEO
```{r Geo_download, message=FALSE, warning=FALSE}
## Download dataset from GEO, save downloaded files in the same folder as this .Rmd file.
dir.create(file.path("raw","gse83933"), recursive = TRUE)
gse83933 <- getGEO("gse83933",  # sample accession 
                   destdir = file.path("raw","gse83933"),
                   GSEMatrix = TRUE,
                   AnnotGPL = TRUE)
```

## Clinical Data from Dataset
```{r ClinicalDataExtract}
## index into data list and extract clinical data
gse83933_cd <- gse83933[["GSE83933_series_matrix.txt.gz"]] %>%   # index into list 
                  phenoData() %>%                                   # select phenoData
                  pData() %>%                                       # apply pData
                  as_tibble() %>%                                   # tidy friendly
                  select("geo_accession" = geo_accession,
                         "sample_id" = title,
                         "sex" = `gender:ch1`, 
                         "grade" = `who grade:ch1`,
                         "radiation" = `history:ch1`
                         ) 

gse83933_pheno <- gse83933_cd %>%         # rename and adjust variables
                      mutate(grade = factor(grade,
                                            levels = c("1", "2", "3"), 
                                            labels = c("I", "II", "III")
                                            ),
                             sex = factor(sex, 
                                           levels = c("male", "female"), 
                                           labels = c("m", "f")
                                           ),
                             radiation = factor(radiation,
                                                   levels =c("No prior radiation history", "prior radiation history"),
                                                   labels = c("no", "yes")
                                                   )  %>% factor(levels =c("yes", "no", "unknown")),
                             tissue = "meningioma"
                    ) %>%
                      mutate_if(is.character, as.factor)
```

## Methylation Data from Dataset
```{r ExpressionDataExtract}
## index into data list and extract methylation table.
gse83933_exprs <- 
                  gse83933[["GSE83933_series_matrix.txt.gz"]] %>%   # index into list 
                  exprs() %>%         # select expression data
                  as_tibble()         # tidy friendly

## index into data list and extract feature data
gse83933_feature <- 
                  gse83933[["GSE83933_series_matrix.txt.gz"]] %>%  # index into list 
                  fData() %>%        # select feature data
                  as_tibble()        # tidy friendly

```

## Transform Methylation Data
``` {r ExpressionDataTransform}
# function to find standard deviation of each probe across all tumors
rowsd <- function(x) {
                      sqrt(
                        rowSums((x - rowMeans(x))^2)/
                          (dim(x)[2] - 1)
                        )
}

gse83933_meth <- bind_cols(gse83933_feature["UCSC_RefGene_Name"], gse83933_exprs) %>% # add gene name to data
               rename("gene" = "UCSC_RefGene_Name") %>%                       # rename name variable as 'gene' 
               filter(gene != "") %>%                                         # keep only data for named genes
               mutate(sd = rowsd(.[,-1])) %>%                                 # calculate sd for each probe, index out gene name
               group_by(gene) %>%                                             # group probes by gene
               filter(sd == max(sd)) %>%                                      # keep the probe with the max variation for each gene
               ungroup() %>%                                                  # ungroup by genes 
               select(-sd) %>%                                                # select all but sd column
               pivot_longer(-gene,                                            # do not group by gene 
                            names_to = "geo_accession",                       
                            values_to = "value") %>%                          
               mutate("mvalue" = log2(value/(1 - value))) %>%                 # log2 transform B / (1-B) expression for variance stabilization 
               group_by(gene) %>%                                             # standardize for cross data set comparison
               mutate("standardized" = (mvalue - mean(mvalue))/               # center at mean for gene 
                                         sd(mvalue),                          # scale by sd for gene
                       ) %>%
                ungroup() %>%                                                 # ungroup by genes 
                select(-value, -mvalue) %>%                                           # select all but sd column
                pivot_wider(names_from = "gene",                              # final format genes as rows
                            values_from = "standardized")                     # final format expression across accession as columns    
```

## Dataset for Analysis
```{r FinalDataset}
## combine phenotype and expression data for workable data
gse83933_data <- inner_join(gse83933_pheno, gse83933_meth, 
                            by = "geo_accession")   # match by accession

## create metatag for dataset
gse83933_info <-  
                list(
                     name = "Agnihotri_S",               # author
                     accession = "GSE83933",         # dataset accession 
                     # the following are logical to determine clinical data available for dataset
                     geo_accession = "geo_accession" %in% colnames(gse83933_pheno),
                      sample_id = "sample_id" %in% colnames(gse83933_pheno),
                      age = "age" %in% colnames(gse83933_pheno),
                      sex = "sex" %in% colnames(gse83933_pheno),
                      grade = "grade" %in% colnames(gse83933_pheno),
                      histology = "histology" %in% colnames(gse83933_pheno),
                      type = "type" %in% colnames(gse83933_pheno),
                      location = "location" %in% colnames(gse83933_pheno),
                      mib1_index = "mib1_index" %in% colnames(gse83933_pheno),
                      recurrence = "recurrence" %in% colnames(gse83933_pheno),
                      recurrence_yrs = "recurrence_yrs" %in% colnames(gse83933_pheno),
                      recurrence_freq = "recurrence_freq" %in% colnames(gse83933_pheno),
                      followup_days = "followup_days" %in% colnames(gse83933_pheno),
                      survival_yrs = "survival_yrs" %in% colnames(gse83933_pheno),
                      vital_indicator = "vital_indicator" %in% colnames(gse83933_pheno),
                      tissue = "tissue" %in% colnames(gse83933_pheno),
                      progression = "progression" %in% colnames(gse83933_pheno),
                      radiation = "radiation" %in% colnames(gse83933_pheno),
                      rna_integrity ="rna_integrity" %in% colnames(gse83933_pheno),

                     sample_numbers = nrow(gse83933_data) # number of samples 
                     )

## create dataset as list 
Agnihotri_S_2013 <- list(
                dataset_info = gse83933_info,             # metatag
                clinical_data = gse83933_pheno,           # clinical data
                expression_data = gse83933_meth,           # expression data
                data = gse83933_data #,                     # combined, workable data
             #   full_GEO = gse83933                       # full original download from GEO
)
```

```{r}
save(Agnihotri_S_2013, file = here("datasets/methylation","GSE83933_Agnihotri_S.Rda")) 
```